# Override Compose file for experimental Time Series mode.
services:
  vippet:
    environment:
      SIMPLE_VIEW_VISIBLE_ELEMENTS: "*src,urisourcebin,gva*,*sink,source,videoscale,tsam-udf"
      SIMPLE_VIEW_INVISIBLE_ELEMENTS: "gvafpscounter,gvametapublish,gvametaconvert,gvawatermark"
      TSAM_HOST: ${TSAM_HOST:-ia-time-series-analytics-microservice}
      TSAM_KAPACITOR_PORT: ${TSAM_KAPACITOR_PORT:-9092}
    depends_on:
      model-download:
        condition: service_healthy
      ia-time-series-analytics-microservice:
        condition: service_started

  ia-timeseries-ingestion:
    build:
      context: ./timeseries-ingestion
      dockerfile: ./Dockerfile
      args:
        TIMESERIES_USER_NAME: ${TIMESERIES_USER_NAME}
        TIMESERIES_UID: ${TIMESERIES_UID}
    container_name: ia-timeseries-ingestion
    image: ${DOCKER_REGISTRY}intel/ia-timeseries-ingestion:${IMAGE_SUFFIX:-latest}${WEEKLY_BUILD_DATE:+-${WEEKLY_BUILD_DATE}}${WEEKLY_BUILD_DATE:+-weekly}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      HOST: ia-time-series-analytics-microservice
      PORT: 5000
      TOPIC: wind-turbine-data
      METADATA_DIR: /metadata
      no_proxy: "ia-time-series-analytics-microservice,${no_proxy}"
      NO_PROXY: "ia-time-series-analytics-microservice,${no_proxy}"
      PYTHONUNBUFFERED: 1
    volumes:
      - ./timeseries-ingestion/input:/app/input:ro
      - ./shared/metadata/:/metadata

  ia-time-series-analytics-microservice:
    container_name: ia-time-series-analytics-microservice
    hostname: ia-time-series-analytics-microservice
    image: ${DOCKER_REGISTRY}intel/ia-time-series-analytics-microservice:${IMAGE_SUFFIX:-latest}${WEEKLY_BUILD_DATE:+-${WEEKLY_BUILD_DATE}}${WEEKLY_BUILD_DATE:+-weekly}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9092/kapacitor/v1/ping"]
      interval: 10s
      timeout: 5s
      retries: 20
    environment:
      no_proxy: "ia-time-series-analytics-microservice,localhost"
      NO_PROXY: "ia-time-series-analytics-microservice,localhost"
      KAPACITOR_PORT: 9092
      INFLUX_SERVER: ""
      KAPACITOR_INFLUXDB_0_USERNAME: ""
      KAPACITOR_INFLUXDB_0_PASSWORD: ""
      PROFILING_MODE: "false"
      KAPACITOR_URL: http://ia-time-series-analytics-microservice:9092
      KAPACITOR_UNSAFE_SSL: "true"
      KAPACITOR_INFLUXDB_0_URLS_0: ""
      INFLUXDB_PORT:
      KAPACITOR_LOGGING_LEVEL: INFO
      INFLUXDB_DBNAME: ""
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      UDF_MAX_FILE_SIZE_MB: 100
      SAMPLE_APP: "wind-turbine-anomaly-detection"
    ports:
      - 5000:5000
    volumes:
      - vol_temp_time_series_analytics_microservice:/tmp/
      - /dev/dri:/dev/dri:ro
      - /run/udev:/run/udev:ro
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "109"
      - "110"
      - "992"

volumes:
  vol_temp_time_series_analytics_microservice:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs