{{- include "chatqna-core.validateGpuSettings" . }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatqna-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatqna-core
  template:
    metadata:
      labels:
        app: chatqna-core
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        {{- if .Values.gpu.enabled }}
        {{- with .Values.gpu.supplementalGroups }}
        supplementalGroups:
{{ toYaml . | indent 10 }}
        {{- end }}
        {{- end }}
      containers:
        - name: chatqna-core
          {{- if eq (.Values.global.MODEL_RUNTIME | lower) "ollama" }}
          image: "{{ .Values.image.registry }}chatqna:{{ .Values.image.tags.ollama }}"
          {{- else }}
          image: "{{ .Values.image.registry }}chatqna:{{ if .Values.gpu.enabled }}{{ .Values.image.tags.openvinoGPU }}{{ else }}{{ .Values.image.tags.openvinoCPU }}{{ end }}"
          {{- end }}
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext:
            privileged: false
          readinessProbe:
            httpGet:
              path: {{ .Values.chatqna.readinessProbe.httpGet.path }}
              port: {{ .Values.chatqna.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.chatqna.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.chatqna.readinessProbe.periodSeconds }}
          env:
            - name: http_proxy
              value: "{{ .Values.global.http_proxy }}"
            - name: https_proxy
              value: "{{ .Values.global.https_proxy }}"
            - name: no_proxy
              value: "{{ .Values.global.no_proxy }},127.0.0.1"
            {{- if eq (.Values.global.MODEL_RUNTIME | lower) "openvino" }}
            - name: HF_ACCESS_TOKEN
              value: "{{ .Values.global.huggingface.apiToken }}"
            {{- end }}
          {{ if .Values.gpu.enabled }}
          resources:
            requests:
              {{ .Values.gpu.key}}: 1
            limits:
              {{ .Values.gpu.key}}: 1
          {{ end }}
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: model-cache
              mountPath: "{{ .Values.global.model_cache_path }}"
            {{- if .Values.configmap.enabled }}
            - name: model-config
              mountPath: /tmp/model_config/config.yaml
              subPath: config.yaml
            {{- end }}
            {{- if .Values.gpu.enabled }}
            - name: dri-device
              mountPath: {{ .Values.gpu.devices }}
            {{- end }}
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: chatqna-pvc
        {{- if .Values.configmap.enabled }}
        - name: model-config
          configMap:
            name: model-config
        {{- end}}
      {{- if .Values.gpu.enabled }}
        - name: dri-device
          hostPath:
            path: {{ .Values.gpu.devices }}
            type: Directory
      {{- end }}
